sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 123456
  alioss:
    endpoint: oss-cn-shenzhen.aliyuncs.com
    access-key-id: LTAI5tNeccJwteJtxpa3Xtaj
    access-key-secret: rLRhmNUzAT8JPaCczOwDGvQmmdw2rk
    bucket-name: bucket-pl
  redis:
    host: localhost
    password: 123456
    port: 6379
    database: 10
  wechat:
    appid: wxbe806ee00dd4e627
    secret: 78c36cd9e98d944348488ee66d1f4ee0
    mchid: 1561414331
    mch-serial-no: 4B3B3DC35414AD50B[B755BAF8DE9CC7CF407606
    private-key-file-path: 4B3B3DC35414AD50B[B755BAF8DE9CC7CF407606
    api-v3-key: CZBK51236435wxpay435434323FFDuv3
    we-chat-pay-cert-file-path: D:\pay\wechatpay_166D96F876F45C7D07CE98952A96EC980368ACFC.pem
    notify-url: https ://6619cf50.r6.cpolar.top/notify/paySuccess
    refund-notify-url: https://6619cf50.r6.cpolar.top/notify/refundSuccess


