sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 123456
  alioss:
    endpoint: oss-cn-shenzhen.aliyuncs.com
    access-key-id: LTAI5tNeccJwteJtxpa3Xtaj
    access-key-secret: rLRhmNUzAT8JPaCczOwDGvQmmdw2rk
    bucket-name: bucket-pl
  redis:
    host: localhost
    password: 123456
    port: 6379
    database: 10
  wechat:
    appid: wxbe806ee00dd4e627
    secret: 78c36cd9e98d944348488ee66d1f4ee0

